# Configuração Netlify - Deploy estático com proxy para backend Replit
# Use este arquivo quando fizer deploy manual de arquivos já compilados

# Redirects para conectar frontend (Netlify) com backend (Replit)
[[redirects]]
  from = "/api/*"
  to = "https://55685bc3-a504-4dcf-b4df-52a026ad255f-00-pmczgzyup1y0.janeway.replit.dev/api/:splat"
  status = 200
  force = true

# Redirect SPA - todas as rotas para index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers para segurança
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Headers para arquivos estáticos
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
