# Configuração para Deploy no Netlify - DTTools
[build]
  command = "npm install && npm run build && cp -r server/public/* dist/public/"
  publish = "dist/public"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

# Redirects para SPA e API - Proxy para Railway backend
[[redirects]]
  from = "/api/*"
  to = "https://dttools-app-production.up.railway.app/api/:splat"
  status = 200
  force = true

# Servir clear-cache.html como arquivo estático (não redirecionar para SPA)
[[redirects]]
  from = "/clear-cache.html"
  to = "/clear-cache.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers para segurança
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Headers para arquivos estáticos
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache-busting para assets JS/CSS - força reload
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Sem cache para index.html - sempre fresh
[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"