services:
  - type: web
    name: dttools-app
    runtime: node
    plan: free
    branch: main
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /api/auth/me
    envVars:
      - key: NODE_ENV
        value: production
      - key: SESSION_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: dttools-db
          property: connectionString
      - key: PORT
        value: 10000

databases:
  - name: dttools-db
    plan: free
    databaseName: dttools
    user: dttools
